### ISSUE TITLE
about the cnn model

### ISSUE THREAD

**Issue by TobyTongg** [k-m-irfan/microexpression_recognition#2]
Do you have any requirements for the network model? I trained with resnet18 and the effect was improved, but it could not be identified accurately.

**Comment by k-m-irfan** [comment]
> Do you have any requirements for the network model? I trained with resnet18 and the effect was improved, but it could not be identified accurately.

no

**Comment by TobyTongg** [comment]
So in theory, I can train it with other network models, right？

**Comment by k-m-irfan** [comment]
Yes
