### ISSUE TITLE
A doubt

### ISSUE THREAD

**Issue by YUZHIWANG-bug** [k-m-irfan/microexpression_recognition#3]
Dear author, it is a great honor to see your project, but I would like to raise a suspicion that your title seems not very good. I think your project is more about macro expression recognition than micro expression recognition, and your data set contains pictures that are macro expressions, and the test set is also macro expressions. Besides, it does not use the usual processing methods for micro-expressions, so I think your project does not have the ability to recognize micro-expressions.

**Comment by k-m-irfan** [comment]
Thanks!
and yes you are right!, it's more towards macro-expressions than micro-expressions

**Comment by YUZHIWANG-bug** [comment]
> Thanks! and yes you are right!, it's more towards macro-expressions than micro-expressions

Thank you for your reply, I have to say that this is a wonderful project, which will be very enlightening to me.

**Comment by k-m-irfan** [comment]
Glad you found it useful!
